name: vacation
description: "Side Project During Vacation"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  build_runner: ^2.4.15
  flutter_secure_storage: ^9.2.4
  get_it: ^8.0.3  # 의존성 주입
  injectable: ^2.5.0  # 의존성 주입
  logger: ^2.5.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  copy_with_extension: ^6.0.1
  either_dart: ^1.0.0
  envied: ^1.1.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  drift: ^2.26.1
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  copy_with_extension_gen: ^6.0.1
  envied_generator: ^1.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  drift_dev: ^2.26.1

flutter:
  uses-material-design: true
